############### 
# TMUX SETUP:
############### 

source-file ~/dotfiles/TOOLS/TMUX/tmux-settings.tmux.conf
#-- enabling quick tmux binding for linux MBA
source-file ~/dotfiles/TOOLS/TMUX/tmux-bindings.conf
source-file ~/dotfiles/TOOLS/TMUX/tmux-status-bar.conf
source-file ~/dotfiles/TOOLS/TMUX/tmux-plugins.conf


# .
