############### 
# TMUX BASIC:
############### 

# open tmux command line
# <leader> : 
# RELOAD TMUX
# :source ~/.tmux.conf

# turn on ability to mouse scroll
# NOTE: only works in terminal and not vim/neovim
# if off then can scroll in vim/neovim but not terminal
#set -g mouse on 

# ALTERNATIVE: to scroll in terminal only when needed
# enters tmux scroll mode
# enter COPY MODE
#<leader> [ 
# to exit just press 'q' or 'esc' or ctrl+c if that doesn't work


# to use vim search commands when in tmux scroll mode
set-window-option -g mode-keys vi


# OPEN TIME
#<leader> t
# to exit just press enter

############### 
# SESSION:
############### 

# to create a NEW SESSION
#$ tmux (new -s <session-name>) 
# to RENAME a (target) SESSION
#$ tmux rename-session -t <old-session-name> <new-session-name> 
# NOTE: you can do this within the session or outside of it
# to KILL a (target) SESSION
#$ tmux kill-session -t <session-name> 

# to LIST all SESSIONS
#$ tmux ls
# to DETACH from a SESSION
#<leader> d
# to ATTACH to a (target) SESSION
#$ tmux attach -t <session-name|ex:n=0-99>

# to SWITCH SESSION
#<leader> s

############### 
# WINDOW:
############### 

# SETTINGS:
set -g base-index 1 #// windows not start at zero index
set -g renumber-windows on #// windows 1,2(x),3 -> 1,2 not 1,3
set -g window-style 'bg=colour234,fg=colour247' #// inactive style
# colour 234 = grey11
# colour 247 = grey62
set -g window-active-style 'bg=colour232,fg=colour244' # -- active style
# color 232 = grey3
# color 244 = grey50

# CREATE A NEW WINDOW
#<leader> c
# rename the current window
#<leader> , 
# OR
#:rename-window <new-name>

# to GO TO a WINDOW use the window key '#'
#<leader> <window #> 
# to go to Next WINDOW (to the window after this one)
#<leader> n 
# to go to Previous WINDOW (to the window before this one)
#<leader> p
# to go to Last WINDOW (to flip between current and last active window)
#<leader> l
# to exit a WINDOW just type exit and press enter 
#$ exit

# to SWAP / SWITCH WINDOWS
# :swap-window -s <src-window-index> -t <target-window-index>




# . 
