############### 
# TMUX BASIC:
############### 

# open tmux command line
# <leader> : 
# RELOAD TMUX
# :source ~/.tmux.conf

# turn on ability to mouse scroll
# NOTE: only works in terminal and not vim/neovim
# if off then can scroll in vim/neovim but not terminal
#set -g mouse on 

# ALTERNATIVE: to scroll in terminal only when needed
# enters tmux scroll mode
# enter COPY MODE
#<leader> [ 
# to exit just press 'q' or 'esc' or ctrl+c if that doesn't work


# to use vim search commands when in tmux scroll mode
set-window-option -g mode-keys vi


# open time
#<leader> t
# to exit just press enter



# . 
