############### 
# TMUX PLUGINS:
############### 

# RELOAD tmux environment with plugins
#$ tmux source ~/.tmux.conf
#<leader> :source ~/.tmux.conf

# PLUGINS INSTALL:
#<leader> I

# PLUGINS UPDATE:
#<leader> U

# PLUGINS UNINSTALL: 
#<leader> alt u

set -g @plugin 'tmux-plugins/tpm'
# see:
#   https://github.com/tmux-plugins/tpm

# -[ ] clone repo: Tmux Plugin Manager (tpm)
#git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# should create the ~/.tmux/ directory and allow for plugin installs
# -[ ] reload TMUX 
# -[ ] install plugins 

# EX:
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@bitbucket.com:user/plugin'

###############
# BASIC SETTINGS:
###############
set -g @plugin 'tmux-plugins/tmux-sensible'

###############
# COLORSCHEME:
###############
#set -g @plugin 'rose-pine/tmux'
#set -g @rose_pine_variant 'moon' # Options are 'main', 'moon' or 'dawn'
# I don't like the setup
# but I can use it to figure it out my custom

#set -g @plugin 'egel/tmux-gruvbox'
#set -g @tmux-gruvbox 'dark'
#set -g @tmux-gruvbox 'light'
# this colorscheme is better but forces arrow styles
# I still prefer simpler


###############
# SESSIONS:
###############
set -g @plugin 'tmux-plugins/tmux-resurrect' # to save sessions accross system restarts
#<leader> ctrl+s // to save
#<leader> ctrl+r // to restore
#set -g @resurrect-save 'S'
#set -g @resurrect-restore 'R'
# -- this appears to not be working anymore

###############
# POMODORO:
###############
set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @pomodoro_start 'b' # key binding to start <leader> + b
set -g @pomodoro_cancel 'B'
set -g @pomodoro_cancel 'B'
set -g @pomodoro_mins 25 # FOCUS
set -g @pomodoro_break_mins 5 # BREAK
set -g @pomodoro_on "#[fg=$text_green]♻️ " 
set -g @pomodoro_complete "#[fg=$text_red]☑️ " 
set -g @pomodoro_notifications 'on'
set -g @pomodoro_sound 'Pop'


# INITIALIZE TMUX plugin manager (keep at bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# .
