############### 
# TMUX BINDINGS:
############### 

# enable <leader> r to reload tmux
unbind r
bind r source-file ~/.tmux.conf

#enabling quick tmux binding for linux MBA
unbind C-b;
set-option -g prefix `;
#bind ` send-prefix
#-- secondary prefix binding
set-option -g prefix2 C-b;

# NAVIGATE BETWEEN PANES
#<leader> <left-arrow>|<up-arrow>|<down-arrow>|<right-arrow>
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# RESIZE PANE TO THE LEFT
bind-key -n C-h resize-pane -L 5
# Resize pane to the downward
bind-key -n C-j resize-pane -D 5
# Resize pane to the upward
bind-key -n C-k resize-pane -U 5
# Resize pane to the right
bind-key -n C-l resize-pane -R 5
