############### 
# TMUX PLUGINS:
############### 
# see: https://github.com/tmux-plugins/tpm
# []- clone repo: Tmux Plugin Manager (tpm)
#$ git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# should create the ~/.tmux/ directory and allow for plugin installs

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # basic tmux settings
set -g @plugin 'tmux-plugins/tmux-resurrect' # to save sessions accross system restarts
#<leader> ctrl+s // to save
#<leader> ctrl+r // to restore
# EX:
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @pomodoro_start 'b' # key binding to start <leader> + b
set -g @pomodoro_cancel 'B'
set -g @pomodoro_cancel 'B'
set -g @pomodoro_mins 25 # FOCUS
set -g @pomodoro_break_mins 5 # BREAK
set -g @pomodoro_on "#[fg=$text_green]♻️ " 
set -g @pomodoro_complete "#[fg=$text_red]☑️ " 
set -g @pomodoro_notifications 'on'
set -g @pomodoro_sound 'Pop'

# RELOAD tmux environment with plugins
#$ tmux source ~/.tmux.conf
#<leader> :source ~/.tmux.conf

# INSTALL plugins
#<leader> I

# UPDATE plugins
#<leader> U

# UNINSTALL plugins
#<leader> alt u

# INITIALIZE TMUX plugin manager (keep at bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# .
