############### 
# TMUX STATUS BAR:
############### 

# set status bar background color
#set -g status-bg colour53 # deep pink4
set -g status-bg colour234 # grey11
#set -g status-bg colour234 # grey11
#set -g status-bg colour235 # grey15
# set status bar foreground color
#set -g status-fg colour255 # grey93
set -g status-fg colour244 # grey50

set -g status-left '#{session_name}_';
set -g window-status-format '#W#F';
# -- #W = window name
# -- #F = window flags
set -g window-status-current-format '#[fg=colour255]#W#F';

set -g status-right-length 100
#set -g status-right "[#(battery Discharge)] %Y-%m%b-%d%a %T %Z"
#set -g status-right "#H #{pomodoro_status}%Y-%m%b%d%a #[fg=colour255]%T#[fg=colour244]%Z"
#set -g status-right "#H #{pomodoro_status}%Y-%m%dw%W%a #[fg=colour255]%T#[fg=colour244]%Z"
set -g status-right "#H #{pomodoro_status}%Y-%m%dw%W%a #[fg=colour255]%H%M:%S#[fg=colour244]%Z"
# NOTE: #H / hostname is weird if you don't have your VPN on 
# NOTE: strftime python used for datetime codes

# for remote linux simplify the status bar
if-shell "uname | grep -q Linux" "\
    set -g status-left '#{session_name}_'; \
    set -g window-status-format '#W#F'; \
    set -g window-status-separator ' '; \
    set -g status-right '%Y%m%d#[fg=colour255]%H%M#[fg=colour244]%Z'; \
    set -g window-status-current-format '#[fg=colour255]#W#F'; "
    #set -g window-status-current-format '#[fg=colour255]#I:#W#F'; "



# . 
